# Generated by Django 3.0.6 on 2020-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_contact_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.CharField(max_length=200)),
                ('new_name', models.CharField(max_length=200)),
                ('new_email_date', models.CharField(max_length=200)),
            ],
        ),
    ]
