# Generated by Django 3.2.7 on 2021-09-20 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_new_contact_list'),
    ]

    operations = [
        migrations.DeleteModel(
            name='new_contact_list',
        ),
    ]
